name: mobilite_moderne
description: Application a destination des réparateurs de vélo / scooter électrique

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: ^7.4.0

  #Firebase
  cloud_firestore: ^4.9.2
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  google_sign_in: ^6.1.5
  flutter:
    sdk: flutter
  
  #Code
  dartz: ^0.10.0-nullsafety.2
  flutter_hooks: ^0.20.1
  flutter_riverpod: ^2.4.0
  injectable: ^2.3.0
  encrypt: ^5.0.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1 #Annotation pour Freezed
  kt_dart: ^1.1.0 #Fonction de Kotlin
  get_it: ^7.6.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  uuid: ^3.0.7 #Crypt
  #shared_preference

  #UI
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.5
  flutter_slidable: ^3.0.0 #Pour faire glisser des éléments et faire apparaitres des boutons supprimer / modifier
  intl: ^0.18.0 #Internationnal pour les formats de date / format de nombre
  implicitly_animated_reorderable_list: ^0.4.2 #Liste réordonnalbe
  easy_sidemenu: ^0.5.0 #Menu à gauche
  flutter_signin_button: ^2.0.0 #Bouton Google / Facebook / Apple ...
  another_flushbar: ^1.12.30
  auto_size_text: ^3.0.0 #Texte qui prend la bonne taille

  #Autre
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^4.1.0 #Récupère les numéros de version de l'app (1.0.0-12)
  dartdoc: ^6.3.0
  flutter_cached_pdfview: ^0.4.2
  video_player: ^2.7.2
  chewie: ^1.7.1
  url_launcher: ^6.1.14
  algolia: ^1.1.2
  webview_flutter: ^4.2.4
  image_picker: ^1.0.4
  flutter_stripe: ^9.4.0
  flutter_stripe_web: ^4.4.0


dev_dependencies:
  build_runner: ^2.4.6 #Génère du code automatiquement
  connectivity_plus: ^4.0.1 #Test la connexion internet de l'appareil
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.6
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.1.2 #Règles pour un code propre
  test: ^1.21.4
  auto_route_generator: ^7.3.1
  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.3.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#42a5f5"
  #background_image: "assets/splash.png"
  web: false

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - config/
    - assets/icon/icon.png
    - assets/icon/icon.png
    - assets/background/assistance-diagnostic.jpg
    - assets/background/assistance.jpg
    - assets/background/compte.jpg
    - assets/background/fond-menuweb.jpg
    - assets/background/mediatheque.jpg
    - assets/background/notice-constructeur.jpg
    - assets/background/piece-fournisseur.jpg
    - assets/background/ressource.jpg
    - assets/background/visio-assistance.jpg
    - assets/background/velo-futuriste.jpeg
  fonts:
    - family: Onest
      fonts:
        - asset: fonts/onest/Onest-ExtraLight.ttf
          weight: 200
        - asset: fonts/onest/Onest-Light.ttf
          weight: 300
        - asset: fonts/onest/Onest-Medium.ttf
          weight: 400
        - asset: fonts/onest/Onest-Regular.ttf
          weight: 500
        - asset: fonts/onest/Onest-SemiBold.ttf
          weight: 600
        - asset: fonts/onest/Onest-Bold.ttf
          weight: 700
        - asset: fonts/onest/Onest-ExtraBold.ttf
          weight: 800
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf