// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4p9Cry_6RvKlsvg17OMQ11C7ckI2kEjs',
    appId: '1:722897713075:web:696176e32e4135b7757dc6',
    messagingSenderId: '722897713075',
    projectId: 'suptek-digital',
    authDomain: 'suptek-digital.firebaseapp.com',
    storageBucket: 'suptek-digital.appspot.com',
    measurementId: 'G-4V9QK7D648',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCovc5Yzmy28LGElNyeGVXMQYaKLG1qqFc',
    appId: '1:722897713075:android:4bccaa7d013bf627757dc6',
    messagingSenderId: '722897713075',
    projectId: 'suptek-digital',
    storageBucket: 'suptek-digital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgA7UDpJsUq729KDBoUL2IOqxblMvjMp8',
    appId: '1:722897713075:ios:193efc57ed238462757dc6',
    messagingSenderId: '722897713075',
    projectId: 'suptek-digital',
    storageBucket: 'suptek-digital.appspot.com',
    iosBundleId: 'com.alban.mobilitemoderne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgA7UDpJsUq729KDBoUL2IOqxblMvjMp8',
    appId: '1:722897713075:ios:193efc57ed238462757dc6',
    messagingSenderId: '722897713075',
    projectId: 'suptek-digital',
    storageBucket: 'suptek-digital.appspot.com',
    iosBundleId: 'com.alban.mobilitemoderne',
  );
}
