// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUGCipQFvWW5yyOKlQhtPMpNMKlMwplmg',
    appId: '1:504195622727:web:d27b4ca4956f678e1a4e62',
    messagingSenderId: '504195622727',
    projectId: 'mobilite-moderne',
    authDomain: 'mobilite-moderne.firebaseapp.com',
    storageBucket: 'mobilite-moderne.appspot.com',
    measurementId: 'G-8K6T7Q1P28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJiTD-ch4dC7rcEMYGNoSvklX-PavBpTU',
    appId: '1:504195622727:android:5b0712bd325a92971a4e62',
    messagingSenderId: '504195622727',
    projectId: 'mobilite-moderne',
    storageBucket: 'mobilite-moderne.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCunX3-UV0WQBMyMtxNK4JNQ7h17mXBh14',
    appId: '1:504195622727:ios:c93b151f213104011a4e62',
    messagingSenderId: '504195622727',
    projectId: 'mobilite-moderne',
    storageBucket: 'mobilite-moderne.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCunX3-UV0WQBMyMtxNK4JNQ7h17mXBh14',
    appId: '1:504195622727:ios:c93b151f213104011a4e62',
    messagingSenderId: '504195622727',
    projectId: 'mobilite-moderne',
    storageBucket: 'mobilite-moderne.appspot.com',
    iosBundleId: 'com.example.admin',
  );
}
