/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData account_balance = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_contacts = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pan_tool = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assistance = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_noir = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_blanc = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piece_jointe = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envoyer = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ressources = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distatelier_blanc = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compte = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voir = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distatelier_noir = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
